// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// IRedisCacheRepository is an autogenerated mock type for the IRedisCacheRepository type
type IRedisCacheRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: keys
func (_m *IRedisCacheRepository) Delete(keys []string) error {
	ret := _m.Called(keys)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: key
func (_m *IRedisCacheRepository) Get(key string) (string, bool) {
	ret := _m.Called(key)

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetPreviousSecretKey provides a mock function with given fields:
func (_m *IRedisCacheRepository) GetPreviousSecretKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSecretKey provides a mock function with given fields:
func (_m *IRedisCacheRepository) GetSecretKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSecretKeyValue provides a mock function with given fields:
func (_m *IRedisCacheRepository) GetSecretKeyValue() (string, bool) {
	ret := _m.Called()

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func() (string, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetStructData provides a mock function with given fields: key, data
func (_m *IRedisCacheRepository) GetStructData(key string, data interface{}) bool {
	ret := _m.Called(key, data)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, interface{}) bool); ok {
		r0 = rf(key, data)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HGet provides a mock function with given fields: key, field
func (_m *IRedisCacheRepository) HGet(key string, field string) (string, error) {
	ret := _m.Called(key, field)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(key, field)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(key, field)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(key, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HGetAll provides a mock function with given fields: key
func (_m *IRedisCacheRepository) HGetAll(key string) (map[string]string, error) {
	ret := _m.Called(key)

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HSet provides a mock function with given fields: key, field, value
func (_m *IRedisCacheRepository) HSet(key string, field string, value string) error {
	ret := _m.Called(key, field, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(key, field, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsExist provides a mock function with given fields: key
func (_m *IRedisCacheRepository) IsExist(key string) bool {
	ret := _m.Called(key)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Lock provides a mock function with given fields: key
func (_m *IRedisCacheRepository) Lock(key string) bool {
	ret := _m.Called(key)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Put provides a mock function with given fields: key, value, timeout
func (_m *IRedisCacheRepository) Put(key string, value interface{}, timeout time.Duration) error {
	ret := _m.Called(key, value, timeout)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, time.Duration) error); ok {
		r0 = rf(key, value, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Scan provides a mock function with given fields: pattern
func (_m *IRedisCacheRepository) Scan(pattern string) ([]string, error) {
	ret := _m.Called(pattern)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(pattern)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unlock provides a mock function with given fields: key
func (_m *IRedisCacheRepository) Unlock(key string) bool {
	ret := _m.Called(key)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewIRedisCacheRepository creates a new instance of IRedisCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRedisCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRedisCacheRepository {
	mock := &IRedisCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
