package response

// basic
const (
	CODE_SUCCESS = 0

	CODE_INTERNAL_ERROR = 1
)

// api
const (
	CODE_API_INVALID_PARAMETER      = 10001
	CODE_API_ILLEGAL_PARAMETER      = 10002
	CODE_API_INTERNAL_SERVER_ERROR  = 10003
	CODE_TIME_INTERVAL_IS_TOO_LONG  = 10004
	CODE_TIME_INTERVAL_IS_TOO_SHORT = 10005
	CODE_MANIPULATE_FAILED          = 10006
	CODE_PARSE_API_RESPONSE_ERROR   = 10007
	CODE_API_REQUEST_TOO_FREQUENTLY = 10008
)

// ws
const (
	CODE_WS_UPGRADE_FAILED  = 11001
	CODE_WS_PARAMETER_ERROR = 11002
)

// player
const (
	CODE_GET_PLAYER_ERROR                   = 12001
	CODE_PLAYER_RELOGIN                     = 12002
	CODE_GET_PLAYER_INFO_ERROR              = 12003
	CODE_PLAYER_MONEY_NOT_ENOUGH            = 12004
	CODE_PLAYER_BET_ERROR                   = 12005
	CODE_PLAYER_BET_MONEY_IS_OUT_OF_MAX_BET = 12006
	CODE_PLAYER_CURRENT_ROUND_HAS_BET       = 12007
	CODE_PLAYER_LAST_ROUND_NOT_BET          = 12008
	CODE_PLAYER_IS_IN_ANOTHER_GAME          = 12009
	CODE_PLAYER_ACTION_IN_WRONG_STATE       = 12010
	CODE_PLAYER_REQUEST_TOO_FREQUENTLY      = 12011
	CODE_PLAYER_ACTOION_ALREADY_DONE        = 12012
	CODE_PLAYER_ACTOION_IS_NOT_ALLOW        = 12013
	CODE_PLAYER_EVENT_IS_NOT_SUPPOERED      = 12014
	CODE_PLAYER_BET_IS_MUTUALLY_EXCLUSIVE   = 12015
	CODE_GET_PLAYING_INFO_FAILED            = 12016
	CODE_PLAYER_IS_IN_ANOTHER_ROOM_LEVEL    = 12017
	CODE_PLAYER_EVENT_PARAMETER_ILLEGAL     = 12018
	CODE_PLAYER_REGISTERATION_DUPLICATED    = 12019
	CODE_PLAYER_DISABLE_CARD                = 12020
	CODE_PLAYER_IS_NOT_ACTIVE               = 12021
	CODE_PLAYER_CURRENT_ROUND_NOT_BET       = 12022
	CODE_PLAYER_UPDATE_BALANCE_ABNORMAL     = 12023
	CODE_CARD_TYPE_INCORRECT                = 12024
	CODE_PLAYER_REACH_MAX_SELECT_CAMP_TIMES = 12025
)

// game
const (
	CODE_INIT_GAME_ERROR                = 13001
	CODE_GET_GAME_ROOM_ERROR            = 13002
	CODE_GAME_INTERNAL_ERROR            = 13003
	CODE_GET_HUNDRED_BOARD_ERROR        = 13004
	CODE_GAME_IS_NOT_INIT_ERROR         = 13005
	CODE_ROOM_IS_FINISH                 = 13006
	CODE_SYSTEM_MAINTENANCE             = 13007
	CODE_GAME_IS_NOT_BET_STATE_ERROR    = 13008
	CODE_IS_NOT_FREE_GAME               = 13009
	CODE_DUPLICATE_TOKEN                = 13010
	CODE_GAME_BET_AREA_LOCK_ERROR       = 13011
	CODE_IS_NOT_FEATURE_GAME            = 13012
	CODE_CAMP_IS_NOT_EXIST              = 13013
	CODE_GAME_IS_NOT_SELECT_STATE_ERROR = 13014
)

// db
const (
	CODE_DATABASE_ABNORMAL      = 14001
	CODE_DATABASE_NOT_FIND_DATA = 14002
)

// auth error
const (
	CODE_AUTH_UNAUTHORIZED         = 15001
	CODE_AUTH_API_KEY_FAILED       = 15002
	CODE_AUTH_GENERATE_TOKEN_ERROR = 15003
	CODE_AUTH_TOKEN_ERROR          = 15004
	CODE_AUTH_GET_TOKEN_ERROR      = 15005
	CODE_AUTH_DELETE_TOKEN_ERROE   = 15006
	CODE_AUTH_TRUST_IP_FAILED      = 15007
	CODE_AUTH_CONTACT_ADMIN        = 15008
)

// cache
const (
	CODE_CACHE_KEY_COLLISION = 16001
	CODE_CACHE_PUT_ERROR     = 16002
	CODE_CACHE_GET_ERROR     = 16003
	CODE_CACHE_ABNORMAL      = 16004
)

// CMS
const (
	CODE_PERMISSION_IS_NOT_ALLOW                 = 17001
	CODE_CMS_SUPPORT_CURRENCY_NEED_MORE_THAN_ONE = 17002
	CODE_CMS_TOKEN_IS_EMPTY                      = 17003
	CODE_CMS_PLAYER_BALANCE_IS_NOT_ENOUGH        = 17004
	CODE_CMS_SINGLE_WALLET_CAN_NOT_TRANSFER      = 17005
	CODE_CMS_PARAMETERS_IS_REQUIRED              = 17006
	CODE_CMS_TIME_FORMAT_ERROR                   = 17007
	CODE_CMS_TIME_CAN_NOT_MORE_THAN_N_DAY        = 17008
	CODE_CMS_CURRENCY_ABNORMAL_QUANTITY          = 17009
	CODE_CMS_CURRENCY_NOT_SUPPORT                = 17010
	CODE_CMS_SYST_CAN_NOT_DEPOSIT                = 17011
	CODE_CMS_SYST_CAN_NOT_LOGIN_IN_AGENT_SITE    = 17012
	CODE_CMS_AUTH_TRUST_IP_FAILED                = 17013
	CODE_CMS_TRANSFER_FAILED_PLAYER_IS_PLAYING   = 17014

	CODE_CMS_ROLE_IS_EXIST = 17601

	CODE_CMS_CMS_USER_IS_DISABLED          = 17701
	CODE_CMS_CMS_USER_OTP_FAIL             = 17702
	CODE_CMS_CMS_USER_CAN_NOT_OPERATE_SELF = 17703
	CODE_CMS_CMS_USER_IS_EXIST             = 17704
	CODE_CMS_CMS_USER_ACCOUNT_PWD_ERROR    = 17705
	CODE_CMS_CMS_USER_OLD_PWD_ERROR        = 17706

	CODE_AGENT_MONEY_IS_NOT_ENOUGH                      = 17801
	CODE_CMS_AGENT_IS_EXIST                             = 17802
	CODE_CMS_AGENT_CAN_NOT_EDIT_SELF_COMMERCIAL_MODE    = 17803
	CODE_CMS_AGENT_CURRENT_OCCUPY_NEED_MORE_THAN_PARENT = 17804
	CODE_CMS_AGENT_CAN_NOT_EDIT_SELF_CURRENCY           = 17805
	CODE_CMS_AGENT_COMMERCIAL_MODE_SUPPORT_TYPE         = 17806
	CODE_CMS_AGENT_WALLET_MODE_SUPPORT_TYPE             = 17807
	CODE_CMS_AGENT_CAN_NOT_LOGIN_IN_STST_SITE           = 17808
	CODE_CMS_AGENT_NOT_SUPPORT_CURRENCY                 = 17809
	CODE_CMS_AGENT_TRANSFER_RECORD_IS_NOT_DEPOSIT       = 17810
	CODE_CMS_AGENT_IP_IS_EXIST                          = 17811
	CODE_CMS_AGENT_FILE_EXPORT_FAIL                     = 17812
	CODE_CMS_AGENT_FILE_UPLOAD_FAIL                     = 17813
	CODE_CMS_AGENT_CAN_NOT_OPERATE_SELF                 = 17814
	CODE_CMS_AGENT_LOBBY_TYPE_WRONG                     = 17815

	CODE_CMS_SERVER_ERROR_BY_DATABASE        = 17901
	CODE_CMS_SERVER_ERROR_BY_REDIS           = 17902
	CODE_CMS_SERVER_ERROR_BY_JSON            = 17903
	CODE_CMS_SERVER_ERROR_BY_FILE_TRAVERSE   = 17904
	CODE_CMS_SERVER_ERROR_BY_FILE_PERMISSION = 17905
)

const (
	CODE_SYSTEM_MAINTENANCE_MODE = 18001
)

// Single Wallet
const (
	CODE_SINGLE_WALLET_INTERNAL_ERROR                 = 20001
	CODE_SINGLE_WALLET_SESSION_ID_ERROR               = 20002
	CODE_SINGLE_WALLET_TRANSFER_ALREADY_DONE          = 20003
	CODE_SINGLE_WALLET_TRANSFER_WITHDRAW_IS_NOT_EXIST = 20004
	CODE_SINGLE_WALLET_API_TIMEOUT_ERROR              = 20005
	CODE_SINGLE_WALLET_PLAYER_MONEY_IS_NOT_ENOUGH     = 20006
	CODE_SINGLE_WALLET_PLAYER_CURRENCY_IS_NOT_SUPPORT = 20007
	CODE_SINGLE_WALLET_AGENT_MONEY_IS_NOT_ENOUGH      = 20008
	CODE_SINGLE_WALLET_THE_PREVIOUS_ROUND_NOT_SETTLED = 20009
	CODE_SINGLE_WALLET_IS_RETRYING_WITHDRAW           = 20010
	CODE_SINGLE_WALLET_MAX_RETRY_LIMIT_REACHED        = 20011
	CODE_SINGLE_WALLET_API_RESPONSE_FORMAT_ERROR      = 20012
	CODE_SINGLE_WALLET_PLAYER_IS_NOT_EXIST            = 20013
)

// Mailbox
const (
	CODE_MAILBOX_AWARD_IS_REDEEMED       = 30001
	CODE_MAILBOX_AWARD_IS_NOT_EXIST      = 30002
	CODE_MAILBOX_CLAIM_MAIL_ABNORMAL     = 30003
	CODE_MAILBOX_CLAIM_MAIL_IS_NOT_EXIST = 30004
	CODE_MAILBOX_RECEIVE_TYPE_ABNORMAL   = 30005
)

// Agent
const (
	CODE_AGENT_IS_NOT_EXIST                  = 40001
	CODE_AGENT_WALLET_TYPE_ABNORMAL          = 40002
	CODE_AGENT_ERROR_WHEN_PLAYER_TRANSFER_IN = 40003
)

// Platform
const (
	CODE_PLATFORM_REQUEST_HEADER_IS_NOT_PLATFORM_NAME    = 50001
	CODE_PLATFORM_CAN_NOT_FIND_PLATFORM_BY_PLATFORM_NAME = 50002
	CODE_PLATFORM_CREATE_PLAYER_ERROR                    = 50003
	CODE_PLATFORM_GET_CURRENCY_ERROR                     = 50004
	CODE_PLATFORM_GET_PLAYER_WALLET_ERROR                = 50005
	CODE_PLATFORM_CREATE_PLAYER_WALLET_ERROR             = 50006
	CODE_PLATFORM_GET_SUPPORT_CURRENCY_ERROR             = 50007
	CODE_PLATFORM_CURRENCY_NOT_SUPPORT                   = 50008
	CODE_PLATFORM_PLAYER_INVALID_ACCOUNT_OR_PASSWOR      = 50009
	CODE_PLATFORM_GET_LOBBY_URL_ERROR                    = 50010
	CODE_PLATFORM_INVALID_DATETIME_FORMAT                = 50011
	CODE_PLATFORM_GET_GAME_URL_ERROR                     = 50012
	CODE_PLATFORM_BET_RECORD_ID_IS_NULL                  = 50013
	CODE_PLATFORM_ROUND_ID_IS_NULL                       = 50014
	CODE_PLATFORM_GET_BET_RECORD_URL_ERROR               = 50015
)
