package response

var API_CODE_MSG_MAP = map[int]string{
	CODE_SUCCESS:        MSG_SUCCESS,
	CODE_INTERNAL_ERROR: MSG_API_INTERNAL_SERVER_ERROR,

	CODE_API_INVALID_PARAMETER: MSG_PARAMETER_ERROR,
	CODE_API_ILLEGAL_PARAMETER: MSG_ILLEGAL_PARAMETER,

	CODE_WS_PARAMETER_ERROR: MSG_WS_QUERY_PARAMETER_ERROR,

	CODE_PLAYER_RELOGIN:                     MSG_PLAYER_RELOGIN,
	CODE_PLAYER_MONEY_NOT_ENOUGH:            MSG_PLAYER_MONEY_NOT_ENOUGH,
	CODE_PLAYER_BET_MONEY_IS_OUT_OF_MAX_BET: MSG_PLAYER_MOENY_IS_OUT_OF_MAX_BET,
	CODE_PLAYER_CURRENT_ROUND_HAS_BET:       MSG_PLAYER_CURRENT_ROUND_HAS_BET,
	CODE_PLAYER_LAST_ROUND_NOT_BET:          MSG_PLAYER_LAST_ROUND_NOT_BET,
	CODE_PLAYER_IS_IN_ANOTHER_GAME:          MSG_PLAYER_IS_IN_ANOTHER_GAME,
	CODE_PLAYER_ACTION_IN_WRONG_STATE:       MSG_PLAYER_ACTION_IN_WRONG_STATE,
	CODE_PLAYER_REQUEST_TOO_FREQUENTLY:      MSG_PLAYER_REQUEST_TOO_FREQUENTLY,
	CODE_PLAYER_ACTOION_ALREADY_DONE:        MSG_PLAYER_ACTOION_ALREADY_DONE,
	CODE_PLAYER_ACTOION_IS_NOT_ALLOW:        MSG_PLAYER_ACTOION_IS_NOT_ALLOW,
	CODE_PLAYER_EVENT_IS_NOT_SUPPOERED:      MSG_PLAYER_EVENT_IS_NOT_SUPPOERED,
	CODE_PLAYER_BET_IS_MUTUALLY_EXCLUSIVE:   MSG_PLAYER_BET_IS_MUTUALLY_EXCLUSIVE,
	CODE_PLAYER_IS_IN_ANOTHER_ROOM_LEVEL:    MSG_PLAYER_IS_IN_ANOTHER_ROOM_LEVEL,

	CODE_DATABASE_ABNORMAL:      MSG_DATABASE_ABNORMAL,
	CODE_DATABASE_NOT_FIND_DATA: MSG_DATABASE_NOT_FIND_DATA,

	CODE_AUTH_UNAUTHORIZED:         MSG_AUTH_UNAUTHORIZED,
	CODE_AUTH_API_KEY_FAILED:       MSG_AUTH_API_KEY_FAILED,
	CODE_AUTH_GENERATE_TOKEN_ERROR: MSG_AUTH_GENERATE_TOKEN_ERROR,
	CODE_AUTH_TOKEN_ERROR:          MSG_AUTH_TOKEN_ERROR,
	CODE_AUTH_GET_TOKEN_ERROR:      MSG_AUTH_GET_TOKEN_ERROR,
	CODE_AUTH_DELETE_TOKEN_ERROE:   MSG_AUTH_DELETE_TOKEN_ERROR,
	CODE_AUTH_TRUST_IP_FAILED:      MSG_AUTH_TRUST_IP_FAILED,
	CODE_AUTH_CONTACT_ADMIN:        MSG_AUTH_CONTACT_ADMIN,

	CODE_CACHE_KEY_COLLISION: MSG_CACHE_KEY_COLLISION,
	CODE_CACHE_PUT_ERROR:     MSG_CACHE_PUT_ERROR,
	CODE_CACHE_GET_ERROR:     MSG_CACHE_GET_ERROR,

	CODE_PERMISSION_IS_NOT_ALLOW: MSG_PERMISSION_IS_NOT_ALLOW,
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}
