package response

var API_CODE_MSG_MAP = map[int]string{
	CODE_SUCCESS:        MSG_SUCCESS,
	CODE_INTERNAL_ERROR: MSG_API_INTERNAL_SERVER_ERROR,

	CODE_API_INVALID_PARAMETER: MSG_PARAMETER_ERROR,
	CODE_API_ILLEGAL_PARAMETER: MSG_ILLEGAL_PARAMETER,

	CODE_WS_PARAMETER_ERROR: MSG_WS_QUERY_PARAMETER_ERROR,

	CODE_PLAYER_RELOGIN:                     MSG_PLAYER_RELOGIN,
	CODE_PLAYER_MONEY_NOT_ENOUGH:            MSG_PLAYER_MONEY_NOT_ENOUGH,
	CODE_PLAYER_BET_MONEY_IS_OUT_OF_MAX_BET: MSG_PLAYER_MOENY_IS_OUT_OF_MAX_BET,
	CODE_PLAYER_CURRENT_ROUND_HAS_BET:       MSG_PLAYER_CURRENT_ROUND_HAS_BET,
	CODE_PLAYER_LAST_ROUND_NOT_BET:          MSG_PLAYER_LAST_ROUND_NOT_BET,
	CODE_PLAYER_IS_IN_ANOTHER_GAME:          MSG_PLAYER_IS_IN_ANOTHER_GAME,
	CODE_PLAYER_ACTION_IN_WRONG_STATE:       MSG_PLAYER_ACTION_IN_WRONG_STATE,
	CODE_PLAYER_REQUEST_TOO_FREQUENTLY:      MSG_PLAYER_REQUEST_TOO_FREQUENTLY,
	CODE_PLAYER_ACTOION_ALREADY_DONE:        MSG_PLAYER_ACTOION_ALREADY_DONE,
	CODE_PLAYER_ACTOION_IS_NOT_ALLOW:        MSG_PLAYER_ACTOION_IS_NOT_ALLOW,
	CODE_PLAYER_EVENT_IS_NOT_SUPPOERED:      MSG_PLAYER_EVENT_IS_NOT_SUPPOERED,
	CODE_PLAYER_BET_IS_MUTUALLY_EXCLUSIVE:   MSG_PLAYER_BET_IS_MUTUALLY_EXCLUSIVE,
	CODE_PLAYER_IS_IN_ANOTHER_ROOM_LEVEL:    MSG_PLAYER_IS_IN_ANOTHER_ROOM_LEVEL,

	CODE_DATABASE_ABNORMAL:      MSG_DATABASE_ABNORMAL,
	CODE_DATABASE_NOT_FIND_DATA: MSG_DATABASE_NOT_FIND_DATA,

	CODE_AUTH_UNAUTHORIZED:         MSG_AUTH_UNAUTHORIZED,
	CODE_AUTH_API_KEY_FAILED:       MSG_AUTH_API_KEY_FAILED,
	CODE_AUTH_GENERATE_TOKEN_ERROR: MSG_AUTH_GENERATE_TOKEN_ERROR,
	CODE_AUTH_TOKEN_ERROR:          MSG_AUTH_TOKEN_ERROR,
	CODE_AUTH_GET_TOKEN_ERROR:      MSG_AUTH_GET_TOKEN_ERROR,
	CODE_AUTH_DELETE_TOKEN_ERROE:   MSG_AUTH_DELETE_TOKEN_ERROR,
	CODE_AUTH_TRUST_IP_FAILED:      MSG_AUTH_TRUST_IP_FAILED,
	CODE_AUTH_CONTACT_ADMIN:        MSG_AUTH_CONTACT_ADMIN,

	CODE_CACHE_KEY_COLLISION: MSG_CACHE_KEY_COLLISION,
	CODE_CACHE_PUT_ERROR:     MSG_CACHE_PUT_ERROR,
	CODE_CACHE_GET_ERROR:     MSG_CACHE_GET_ERROR,

	//cms
	CODE_CMS_PERMISSION_IS_NOT_ALLOW:             MSG_CMS_PERMISSION_IS_NOT_ALLOW,
	CODE_CMS_SUPPORT_CURRENCY_NEED_MORE_THAN_ONE: MSG_CMS_SUPPORT_CURRENCY_NEED_MORE_THAN_ONE,
	CODE_CMS_TOKEN_IS_EMPTY:                      MSG_CMS_TOKEN_IS_EMPTY,
	CODE_CMS_CURRENCY_ABNORMAL_QUANTITY:          MSG_CMS_CURRENCY_ABNORMAL_QUANTITY,
	CODE_CMS_CURRENCY_NOT_SUPPORT:                MSG_CMS_CURRENCY_NOT_SUPPORT,
	CODE_CMS_PLAYER_BALANCE_IS_NOT_ENOUGH:        MSG_CMS_PLAYER_BALANCE_IS_NOT_ENOUGH,
	CODE_CMS_SINGLE_WALLET_CAN_NOT_TRANSFER:      MSG_CMS_SINGLE_WALLET_CAN_NOT_TRANSFER,
	CODE_CMS_PARAMETERS_IS_REQUIRED:              MSG_CMS_PARAMETERS_IS_REQUIRED,
	CODE_CMS_TIME_FORMAT_ERROR:                   MSG_CMS_TIME_FORMAT_ERROR,
	CODE_CMS_TIME_CAN_NOT_MORE_THAN_N_DAY:        MSG_CMS_TIME_CAN_NOT_MORE_THAN_N_DAY,
	CODE_CMS_SYST_CAN_NOT_DEPOSIT:                MSG_CMS_SYST_CAN_NOT_DEPOSIT,
	CODE_CMS_SYST_CAN_NOT_LOGIN_IN_AGENT_SITE:    MSG_CMS_SYST_CAN_NOT_LOGIN_IN_AGENT_SITE,

	CODE_CMS_CMS_USER_IS_DISABLED:          MSG_CMS_CMS_USER_IS_DISABLED,
	CODE_CMS_CMS_USER_OTP_FAIL:             MSG_CMS_CMS_USER_OTP_FAIL,
	CODE_CMS_CMS_USER_CAN_NOT_OPERATE_SELF: MSG_CMS_CMS_USER_CAN_NOT_OPERATE_SELF,
	CODE_CMS_CMS_USER_IS_EXIST:             MSG_CMS_CMS_USER_IS_EXIST,

	CODE_CMS_AGENT_IS_EXIST:                             MSG_CMS_AGENT_IS_EXIST,
	CODE_CMS_AGENT_CAN_NOT_EDIT_SELF_COMMERCIAL_MODE:    MSG_CMS_AGENT_CAN_NOT_EDIT_SELF_COMMERCIAL_MODE,
	CODE_CMS_AGENT_CURRENT_OCCUPY_NEED_MORE_THAN_PARENT: MSG_CMS_AGENT_CURRENT_OCCUPY_NEED_MORE_THAN_PARENT,
	CODE_CMS_AGENT_CAN_NOT_EDIT_SELF_CURRENCY:           MSG_CMS_AGENT_CAN_NOT_EDIT_SELF_CURRENCY,
	CODE_CMS_AGENT_COMMERCIAL_MODE_SUPPORT_TYPE:         MSG_CMS_AGENT_COMMERCIAL_MODE_SUPPORT_TYPE,
	CODE_CMS_AGENT_WALLET_MODE_SUPPORT_TYPE:             MSG_CMS_AGENT_WALLET_MODE_SUPPORT_TYPE,
	CODE_CMS_AGENT_CAN_NOT_LOGIN_IN_STST_SITE:           MSG_CMS_AGENT_CAN_NOT_LOGIN_IN_STST_SITE,
	CODE_CMS_AGENT_IP_IS_EXIST:                          MSG_CMS_AGENT_IP_IS_EXIST,
	CODE_CMS_AGENT_FILE_EXPORT_FAIL:                     MSG_CMS_AGENT_FILE_EXPORT_FAIL,
	CODE_CMS_AGENT_TRANSFER_RECORD_IS_NOT_DEPOSIT:       MSG_CMS_AGENT_TRANSFER_RECORD_IS_NOT_DEPOSIT,
	CODE_CMS_AGENT_FILE_UPLOAD_FAIL:                     MSG_CMS_AGENT_FILE_UPLOAD_FAIL,

	CODE_CMS_SERVER_ERROR_BY_DATABASE:        MSG_CMS_SERVER_ERROR_BY_DATABASE,
	CODE_CMS_SERVER_ERROR_BY_REDIS:           MSG_CMS_SERVER_ERROR_BY_REDIS,
	CODE_CMS_SERVER_ERROR_BY_JSON:            MSG_CMS_SERVER_ERROR_BY_JSON,
	CODE_CMS_SERVER_ERROR_BY_FILE_TRAVERSE:   MSG_CMS_SERVER_ERROR_BY_FILE_TRAVERSE,
	CODE_CMS_SERVER_ERROR_BY_FILE_PERMISSION: MSG_CMS_SERVER_ERROR_BY_FILE_PERMISSION,

	// system
	CODE_SYSTEM_MAINTENANCE_MODE: MSG_SYSTEM_MAINTENANCE_MODE,
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}
